spring.application.name=Spring-java-jpa
spring.datasource.url=jdbc:mysql://localhost:3306/schooldb
spring.datasource.username=root
spring.datasource.password=@Rishi2706
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

//Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details =

management.info.env.enabled = true
info.app.name = Learning Actuators
info.app.description  = Testing all Actuators
info.app.version = 1.0.0
